---
title: "Untitled"
format: html
---

---
title: "My Analysis"
author: "Your Name"
format: 
  html:
    toc: true
    number-sections: true
execute:
  message: false
  warning: false
bibliography: references.bib
---
    
## Setup
```{r}
### Data wrangling packages:
library(readr)
library(dplyr)
library(tidyr)
library(here)

### Simple Features vector spatial data:
library(sf)

### Data visualization packages:
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
```

### Data Exploration
```{r}
out_dir <- here::here('data/ak_regions')

if(!dir.exists(out_dir)) {
    knb_url <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Aaceaecb2-1ce0-4d41-a839-d3607d32bb58"

    download.file(url = knb_url, 
                  destfile = 'shapefile_demo_data.zip', 
                  mode = 'wb')

    unzip('shapefile_demo_data.zip', exdir = out_dir)

    file.remove('shapefile_demo_data.zip')
}
```

## Analysis

```{r}
ak_rgns_sf <- read_sf(here("data/ak_regions_simp.shp"))
```

```{r}
# quick plot
plot(ak_rgns_sf)
```

```{r}
st_crs(ak_rgns_sf)

ak_rgns_3338_sf <- ak_rgns_sf %>%
    st_transform(crs = 3338)

# st_crs(ak_rgns_3338_sf) ### run in console to check
st_crs(ak_rgns_3338_sf)
```

```{r}
# quick plot
plot(ak_rgns_3338_sf)
```

```{r}
class(ak_rgns_3338_sf)
```

```{r}
### select keeps `region` AND `geometry` automatically
ak_rgns_3338_sf %>%
    select(region) %>% 
    head()
```

```{r}
```

```{r}
### filter() works exactly as expected!
ak_rgns_3338_sf %>%
    filter(region %in% c("Arctic", "Kodiak"))
```

```{r}
out_file <- here::here('data/alaska_population.csv')

if(!file.exists(out_file)) {
    pop_data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"

    download.file(url = pop_data_url, 
                  destfile = out_file, 
                  mode = 'w')
}
```

```{r}
pop_df <- read_csv(here("data/alaska_population.csv")) %>%
    filter(year == 2015) %>%
    select(city, lat, lng, population) %>%
    drop_na()
```

```{r}
pop_4326_sf <- st_as_sf(pop_df,
                        coords = c('lng', 'lat'),
                        crs = 4326,
                        remove = FALSE)
head(pop_4326_sf)
```

```{r}
pop_3338_sf <- st_transform(pop_4326_sf, 
                            crs = 3338)

pop_joined_sf <- st_join(pop_3338_sf, 
                         ak_rgns_3338_sf, 
                         join = st_within)
```

```{r}
pop_rgn_df <- pop_joined_sf %>%
    st_drop_geometry() %>%
    group_by(region) %>%
    summarize(total_pop = sum(population))

head(pop_rgn_df)
```

```{r}
pop_rgn_3338_sf <- left_join(ak_rgns_3338_sf, 
                             pop_rgn_df, 
                             by = "region")

### plot to check
plot(pop_rgn_3338_sf["total_pop"])
```

```{r}
## dissolve regions
pop_mgmt_3338_sf <- pop_rgn_3338_sf %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_3338_sf["total_pop"])
```

```{r}
write_sf(pop_rgn_3338_sf, here("data/ak_regions_population.gpkg"))
```


```{r}
ggplot(pop_rgn_3338_sf) +
    geom_sf(aes(fill = total_pop)) +
    labs(fill = "Total Population") +
    scale_fill_continuous(low = "khaki", high =  "firebrick",
                          labels = comma, name = "Population") +
    theme_bw()
```

```{r}
rivers_3338_sf <- read_sf(here("data/ak_rivers_simp.shp"))
ggplot() +
    geom_sf(data = pop_rgn_3338_sf, 
            mapping = aes(fill = total_pop)) +
    geom_sf(data = rivers_3338_sf,
            aes(linewidth = StrOrder),
            color = 'blue', alpha = .5) +
    scale_linewidth(range = c(0.05, 0.5),
                    guide = "none") +
    geom_sf(data = pop_3338_sf, size = 0.5, color = 'grey20') +
    labs(title = "Total Population by Alaska Region",
         fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw() 
```

```{r}
pop_3857_sf <- st_transform(pop_3338_sf, 
                         crs = 3857)
```

```{r}
ggplot(data = pop_3857_sf) +
    ggspatial::annotation_map_tile(type = "osm", zoom = 6, progress = 'none') + 
    # higher zoom values are more detailed 
    geom_sf(aes(color = population),
            fill = NA) +
    coord_sf(xlim = c(-16900000, -16300000), ylim = c(8400000, 9000000)) +
    scale_color_continuous(low = "darkkhaki",
                           high =  "firebrick",
                           labels = comma)
```

```{r}
##if you want to zoom in
ggplot(data = pop_3857_sf) +
    ggspatial::annotation_map_tile(type = "osm", zoom = 6, progress = 'none') + 
    # higher zoom values are more detailed 
    geom_sf(aes(color = population),
            fill = NA) +
              coord_sf(xlim = c(-500000, 600000), ylim = c(900000, 2000000)) +
                  scale_color_continuous(low = "darkkhaki",
                           high =  "firebrick",
                           labels = comma)
```


```{r}
pop_rgn_4326_sf <- pop_rgn_3338_sf %>% 
    st_transform(crs = 4326)
```

```{r}
### set up a palette based on our colors
pal <- colorNumeric(palette = "Reds", domain = pop_rgn_4326_sf$total_pop)

pop_rgn_map <- leaflet(data = pop_rgn_4326_sf) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(
    fillColor  = ~pal(total_pop),           
    fillOpacity = 0.8,
    color      = "white",
    weight     = 1,
    label      = ~paste0(region, ": ", comma(total_pop))
  ) %>%
  addLegend(
    position = "bottomleft",
    pal      = pal,
    values   = ~total_pop,
    title    = "Total Population"
  )

pop_rgn_map
```

```{r}
pop_rgn_map <- pop_rgn_map %>%
    addCircleMarkers(
        data        = pop_4326_sf,
        radius      = ~ log(population / 500),
        fillColor   = "gray",
        fillOpacity = 1,
        weight      = 0.25,
        color       = "black",
        label       = ~ paste0(pop_4326_sf$city,
                               ", population ", 
                               comma(pop_4326_sf$population))
    ) 
pop_rgn_map
```

```{r}
anch_latlong <- pop_df %>%
    filter(city == "Anchorage") %>%
    select(lat, lng)
anch_latlong
pop_rgn_map %>%
    setView(lng = anch_latlong$lng, lat = anch_latlong$lat, zoom = 5)
```

```{r}
city_buffers <- pop_3338_sf |>
  st_buffer(dist = 50000)   ### distance in CRS units (meters for EPSG:3338)

buffered_rgns <- st_intersection(city_buffers, ak_rgns_3338_sf)

plot(buffered_rgns %>% select(region))
```










```{r}
```
